spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH2_KEY}
            client-secret: ${GOOGLE_OAUTH2_SECRET}
            scope:
              - profile
              - email
  thymeleaf3:
    decoupled-logic: true