spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH2_KEY}
            client-secret: ${GOOGLE_OAUTH2_SECRET}
            scope:
              - email
              - https://www.googleapis.com/auth/calendar
              - https://www.googleapis.com/auth/calendar.readonly
              - https://www.googleapis.com/auth/calendar.settings.readonly
  thymeleaf3:
    decoupled-logic: true