spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH2_KEY}
            client-secret: ${GOOGLE_OAUTH2_SECRET}
            scope:
              - email
              - https://www.googleapis.com/auth/calendar
              - https://www.googleapis.com/auth/calendar.readonly
              - https://www.googleapis.com/auth/calendar.settings.readonly
              - https://www.googleapis.com/auth/calendar.events.readonly
              - https://www.googleapis.com/auth/calendar.events
  thymeleaf3:
    decoupled-logic: true
  datasource:
    url: jdbc:h2:mem:alarm
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true